# MySQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-password: dXNlcnBhc3N3b3Jk
---
# MySQL PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/mysql-data
  persistentVolumeReclaimPolicy: Retain
---
# MySQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "ghostdb"
        - name: MYSQL_USER
          value: "ghostuser"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
  namespace: default
spec:
  selector:
    app: mysql-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
# Ghost App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-app
  template:
    metadata:
      labels:
        app: ghost-app
    spec:
      containers:
      - name: ghost
        image: ghost:5
        ports:
        - containerPort: 2368
        env:
        - name: database__client
          value: "mysql"
        - name: database__connection__host
          value: "mysql-db-service"
        - name: database__connection__user
          value: "ghostuser"
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: database__connection__database
          value: "ghostdb"
        - name: url
          value: "http://3.227.245.141:32368"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: 30
          periodSeconds: 10
---
# Ghost Service
apiVersion: v1
kind: Service
metadata:
  name: ghost-app-service
  namespace: default
spec:
  selector:
    app: ghost-app
  ports:
  - port: 2368
    targetPort: 2368
    nodePort: 32368
  type: NodePort
---
# MySQL KEDA Scaler
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mysql-db-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: mysql-db
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "80"
  - type: memory
    metadata:
      type: Utilization
      value: "85"
---
# Ghost KEDA Scaler
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ghost-app-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: ghost-app
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "70"
  - type: memory
    metadata:
      type: Utilization
      value: "80"